version: '3.3'
services:
    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx/core:/etc/nginx/conf.d
            - ./nginx/www:/var/www/
            - ./nginx/logs:/var/log/nginx/
            - ./nginx/html:/usr/share/nginx/html/
        links:
            - php
            - mysql

    mysql:
      image: mysql:latest
      container_name: mysql
      environment:
        MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
        MYSQL_DATABASE: "${DB_NAME}"
        MYSQL_USER: "${DB_USERNAME}"
        MYSQL_PASSWORD: "${DB_PASSWORD}"
      command: --default-authentication-plugin=mysql_native_password
      ports:
        - "3306:3306"
      volumes:
            - ./mysql:/var/lib/mysql


    php:
        build: ./php
        container_name: php-fpm
        volumes:
            - ./nginx/www:/var/www
        links:
            - mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        links:
          - mysql
        environment:
          PMA_HOST: mysql
          PMA_PORT: 3306
        ports:
          - "8090:80"
command: sh curl -s https://wordpress.org/latest.tar.gz | tar xvz  -C ./nginx/www
